### ISSUE TITLE
need a Perl 6 api access tool

### ISSUE THREAD

**Issue by tbrowder** [joshtronic/ruby-holidayapi#1]
Be one of the first companies to have and publish a [Perl 6](https://perl6.org) api wrapper tool.

I'll submit a PR for a Perl 6 tool (in the basic style of the other language api wrappers) if you create a repo named **perl6-holidayapi**.

**Comment by joshtronic** [comment]
https://github.com/joshtronic/perl6-holidayapi :boom:
